-- Generated from packages/core/src/services.ts by `pnpm --filter @i-events/core catalog:sql`. Do not edit.
insert into public.service_categories (key, name, icon, questions, sort) values
  ('organization', '{"it":"Organizzazione e regia","en":"Planning and direction"}'::jsonb, 'clipboard', '[{"key":"scope","type":"select","required":true,"label":{"it":"Cosa serve","en":"What you need"},"options":[{"value":"full","label":{"it":"Gestione completa","en":"Full management"}},{"value":"partial","label":{"it":"Solo coordinamento","en":"Coordination only"}},{"value":"day","label":{"it":"Solo il giorno dell''evento","en":"Event day only"}}]},{"key":"on_site_staff","type":"number","min":0,"label":{"it":"Persone di regia in loco","en":"On-site directors"}},{"key":"notes","type":"text","multiline":true,"label":{"it":"Altre indicazioni","en":"Other notes"}}]'::jsonb, 0),
  ('venue', '{"it":"Location","en":"Venue"}'::jsonb, 'building', '[{"key":"space_type","type":"select","required":true,"label":{"it":"Tipo di spazio","en":"Space type"},"options":[{"value":"private","label":{"it":"Privato","en":"Private"}},{"value":"public","label":{"it":"Pubblico","en":"Public"}},{"value":"either","label":{"it":"Indifferente","en":"Either"}}]},{"key":"setting","type":"select","required":true,"label":{"it":"Ambiente","en":"Setting"},"options":[{"value":"indoor","label":{"it":"Interno","en":"Indoor"}},{"value":"outdoor","label":{"it":"Esterno","en":"Outdoor"}},{"value":"both","label":{"it":"Entrambi","en":"Both"}}]},{"key":"capacity","type":"number","min":1,"unit":"persone","label":{"it":"Capienza richiesta","en":"Required capacity"}},{"key":"city","type":"text","label":{"it":"Città o zona","en":"City or area"}},{"key":"has_venue","type":"boolean","label":{"it":"Abbiamo già una location","en":"We already have a venue"}},{"key":"notes","type":"text","multiline":true,"label":{"it":"Altre indicazioni","en":"Other notes"}}]'::jsonb, 1),
  ('logistics', '{"it":"Logistica e trasporti","en":"Logistics and transport"}'::jsonb, 'truck', '[{"key":"needs","type":"multiselect","required":true,"label":{"it":"Di cosa avete bisogno","en":"What you need"},"options":[{"value":"goods","label":{"it":"Trasporto materiali","en":"Goods transport"}},{"value":"guests","label":{"it":"Navette ospiti","en":"Guest shuttles"}},{"value":"storage","label":{"it":"Magazzino","en":"Storage"}},{"value":"parking","label":{"it":"Parcheggi","en":"Parking"}}]},{"key":"notes","type":"text","multiline":true,"label":{"it":"Altre indicazioni","en":"Other notes"}}]'::jsonb, 2),
  ('av', '{"it":"Service audio, luci e video","en":"Audio, lighting and video"}'::jsonb, 'speaker', '[{"key":"needs","type":"multiselect","required":true,"label":{"it":"Impianti","en":"Equipment"},"options":[{"value":"audio","label":{"it":"Audio","en":"Audio"}},{"value":"lights","label":{"it":"Luci","en":"Lighting"}},{"value":"ledwall","label":{"it":"Ledwall","en":"LED wall"}},{"value":"projection","label":{"it":"Proiezione","en":"Projection"}},{"value":"streaming","label":{"it":"Diretta streaming","en":"Live streaming"}},{"value":"stage","label":{"it":"Palco","en":"Stage"}}]},{"key":"notes","type":"text","multiline":true,"label":{"it":"Altre indicazioni","en":"Other notes"}}]'::jsonb, 3),
  ('entertainment', '{"it":"DJ set e intrattenimento","en":"DJ set and entertainment"}'::jsonb, 'music', '[{"key":"kind","type":"multiselect","required":true,"label":{"it":"Tipo","en":"Type"},"options":[{"value":"dj","label":{"it":"DJ set","en":"DJ set"}},{"value":"live","label":{"it":"Musica dal vivo","en":"Live music"}},{"value":"host","label":{"it":"Presentatore","en":"Host"}},{"value":"performer","label":{"it":"Performer","en":"Performers"}}]},{"key":"genre","type":"text","label":{"it":"Genere o atmosfera","en":"Genre or mood"}},{"key":"hours","type":"number","min":1,"unit":"ore","label":{"it":"Durata","en":"Duration"}},{"key":"notes","type":"text","multiline":true,"label":{"it":"Altre indicazioni","en":"Other notes"}}]'::jsonb, 4),
  ('security', '{"it":"Sicurezza e steward","en":"Security and stewards"}'::jsonb, 'shield', '[{"key":"guards","type":"number","min":0,"label":{"it":"Addetti alla sicurezza","en":"Security staff"}},{"key":"stewards","type":"number","min":0,"label":{"it":"Steward","en":"Stewards"}},{"key":"first_aid","type":"boolean","label":{"it":"Presidio sanitario","en":"First aid station"}},{"key":"notes","type":"text","multiline":true,"label":{"it":"Altre indicazioni","en":"Other notes"}}]'::jsonb, 5),
  ('cleaning', '{"it":"Pulizia","en":"Cleaning"}'::jsonb, 'sparkles', '[{"key":"when","type":"multiselect","required":true,"label":{"it":"Quando","en":"When"},"options":[{"value":"before","label":{"it":"Prima","en":"Before"}},{"value":"during","label":{"it":"Durante","en":"During"}},{"value":"after","label":{"it":"Dopo","en":"After"}}]},{"key":"notes","type":"text","multiline":true,"label":{"it":"Altre indicazioni","en":"Other notes"}}]'::jsonb, 6),
  ('catering', '{"it":"Catering e bar","en":"Catering and bar"}'::jsonb, 'utensils', '[{"key":"format","type":"select","required":true,"label":{"it":"Formula","en":"Format"},"options":[{"value":"cocktail","label":{"it":"Aperitivo / cocktail","en":"Cocktail"}},{"value":"buffet","label":{"it":"Buffet","en":"Buffet"}},{"value":"seated","label":{"it":"Cena servita","en":"Seated dinner"}},{"value":"bar","label":{"it":"Solo bar","en":"Bar only"}}]},{"key":"dietary","type":"text","label":{"it":"Esigenze alimentari","en":"Dietary needs"}},{"key":"notes","type":"text","multiline":true,"label":{"it":"Altre indicazioni","en":"Other notes"}}]'::jsonb, 7),
  ('setup', '{"it":"Allestimento e branding","en":"Set design and branding"}'::jsonb, 'palette', '[{"key":"product_display","type":"boolean","label":{"it":"Esposizione prodotto","en":"Product display"}},{"key":"brand_assets","type":"boolean","label":{"it":"Forniamo noi i materiali del brand","en":"We supply brand assets"}},{"key":"notes","type":"text","multiline":true,"label":{"it":"Altre indicazioni","en":"Other notes"}}]'::jsonb, 8),
  ('staffing', '{"it":"Hostess e promoter","en":"Hosts and promoters"}'::jsonb, 'users', '[{"key":"count","type":"number","min":1,"label":{"it":"Numero","en":"Headcount"}},{"key":"languages","type":"text","label":{"it":"Lingue richieste","en":"Required languages"}},{"key":"notes","type":"text","multiline":true,"label":{"it":"Altre indicazioni","en":"Other notes"}}]'::jsonb, 9),
  ('media', '{"it":"Foto, video e social","en":"Photo, video and social"}'::jsonb, 'camera', '[{"key":"needs","type":"multiselect","required":true,"label":{"it":"Servizi","en":"Services"},"options":[{"value":"photo","label":{"it":"Foto","en":"Photo"}},{"value":"video","label":{"it":"Video","en":"Video"}},{"value":"aftermovie","label":{"it":"Aftermovie","en":"Aftermovie"}},{"value":"social","label":{"it":"Copertura social live","en":"Live social coverage"}},{"value":"influencer","label":{"it":"Influencer","en":"Influencers"}}]},{"key":"notes","type":"text","multiline":true,"label":{"it":"Altre indicazioni","en":"Other notes"}}]'::jsonb, 10),
  ('permits', '{"it":"Permessi e SIAE","en":"Permits and licensing"}'::jsonb, 'file-check', '[{"key":"needs","type":"multiselect","label":{"it":"Pratiche","en":"Paperwork"},"options":[{"value":"siae","label":{"it":"SIAE","en":"Music licensing"}},{"value":"public_land","label":{"it":"Suolo pubblico","en":"Public land"}},{"value":"safety","label":{"it":"Commissione sicurezza","en":"Safety commission"}}]},{"key":"notes","type":"text","multiline":true,"label":{"it":"Altre indicazioni","en":"Other notes"}}]'::jsonb, 11)
on conflict (key) do update set name = excluded.name, icon = excluded.icon, questions = excluded.questions, sort = excluded.sort, active = true;
